### ISSUE TITLE
Provide helper methods for building payloads

### ISSUE THREAD

**Issue by AdityaAnand1** [razorpay/razorpay-android-custom-sample-app#11]
How about some helper methods that take in only the arguments required to build payload and simply return the payload object? This would be a much better approach when we consider building a more helpful example that would scale easily in real apps.

![image](https://user-images.githubusercontent.com/13274079/75157734-bbe09a00-573a-11ea-8528-e290835ae242.png)

```
fun getNetBankingPayload(...) : JSONObject {}

fun getWalletPayload(...) : JSONObject {}
```

Happy to elaborate more if you'd like.

**Comment by sumedht** [comment]
@AdityaAnand1 For this any way we need to pass customer & transaction details. If u can elaborate it, will be helpful to understand
