### ISSUE TITLE
Use kotlin android extensions view binding

### ISSUE THREAD

**Issue by AdityaAnand1** [razorpay/razorpay-android-custom-sample-app#12]
`findViewById` is extremely outdated and should be replaced.

https://proandroiddev.com/kotlin-android-extensions-using-view-binding-the-right-way-707cd0c9e648

**Comment by sumedht** [comment]
@AdityaAnand1 Thanks for suggestion. It's a part of sample application and not SDK which we delivered. Definitely we can take foreword in future.
