### ISSUE TITLE
Caused by: org.gradle.api.InvalidUserDataException: 

### ISSUE THREAD

**Issue by githubashutoshsoni** [razorpay/razorpay-android-custom-sample-app#22]
Caused by: org.gradle.api.InvalidUserDataException: Required keys [path] are missing from map {name=razorpay-android-3.8.8, ext=aar}

also followed all the procedure right. What am I doing wrong?

keep getting this error even when I have enabled this in my manifest
<meta-data
            android:name="com.razorpay.ApiKey"
            android:value="rzp_test_5XXXXXXXX"
            />

**Comment by PraveenGirishNadumani** [comment]
Download the latest SDK from the below link and add the SDK to your lib folder manually 
http://rzp-mobile.s3.amazonaws.com/customui/razorpay-android-3.8.8.aar
after adding the SDK to the lib folder add the below link to the build.gradel file
dependencies {
  implementation(name: "razorpay-android-3.8.8", ext: 'aar')
}

**Comment by techexe-code** [comment]
Same issue 

Required keys [path] are missing from map {name=razorpay-android-3.8.10, ext=aar}.

**Comment by ayush-razorpay** [comment]
1. Place the Razorpay aar file to libs under path app/libs. ([download link](https://rzp-mobile.s3.amazonaws.com/customui/razorpay-android-3.9.0.aar))
​
2. Add the following in app/build.gradle

              Add the following dependency : 
                   compile(name:'razorpay-android-3.9.0', ext:'aar')

Also, add the following to the same file (I added it at the bottom of the file)

repositories{
    flatDir{
        dirs 'libs'
    }
}
