### ISSUE TITLE
UX issue with UPI payment with google pay via razorpay custom sdk

### ISSUE THREAD

**Issue by sudeshim3** [razorpay/razorpay-android-custom-sample-app#45]
## Description

When a user cancels UPI payment through google play. The app is stuck in the loading page for indefinite amount of time.
Please note that other UPI apps are not having the issue (tried with PhonePe and Paytm). 

![image](https://user-images.githubusercontent.com/34063388/113439011-582da380-9407-11eb-90c5-a60a563f24e4.png)

>*Please update google pay to the latest version to validate this issue because it worked fine on older versions of google play*

## Razorpay SDK Version :
razorpay-android-3.9.0

### What you did:

From my investigation, I found that different UPI apps provide different intent data for onActivityResult callback

For example PayTm/PhonePe provides the following flags
![image](https://user-images.githubusercontent.com/34063388/113439227-c7a39300-9407-11eb-8554-a99fa93e1c74.png)

However, google pay provides only the Status flag unlike other apps which give a host of flags to interpret payment status.

![image](https://user-images.githubusercontent.com/34063388/113439387-194c1d80-9408-11eb-9c73-dc6b5706558d.png)

Please help us resolve the issue's so that we overcome the above mentioned UX glitch.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open Razorpay custom sample app. 
2. Go to UPI and select intent flow.
3. Select google pay as your UPI payment option.
4. Swipe back to close google pay.
Now you will find yourself in webview of your app and the page is in a processing state for an indefinite time.

**Comment by sudeshim3** [comment]
@sumedht plz help resolve the above issue. thanks.

**Comment by sumedht** [comment]
@sudeshim3 I will check & get back to u

**Comment by sudeshim3** [comment]
@sumedht any updates on this.

**Comment by vivekshindhe** [comment]
@sudeshim3 We've updated our SDK with this. Please download the latest sdk version and try again. v1.6.7. Closing this issue. Please reopen or create another in case of any other issues.
