### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by AdityaAnand1** [razorpay/razorpay-android-custom-sample-app#9]
* A sample kotlin implementation with the latest android best practices and libraries implemented would be a fantastic help.
* The README should contain a description of the project, the various working parts etc. and some screenshots
* How about a link to a demo APK or play store demo app?

**Comment by sumedht** [comment]
@AdityaAnand1 
- We are on adding a sample code using Kotlin integration.
- We will update Readme
- One can run a Sample app directly. Right now we don't have published Custom-UI app on play store but will provide the path for APK

**Comment by AdityaAnand1** [comment]
Great! Would you mind keeping the issue open until the mentioned changes are implemented? It's polite to new developers who might wonder the same things 😀
